# Decision Tree

In [5]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

cancer = load_iris(as_frame=True)
df = cancer.frame

df.head(5)

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [6]:
X = df.drop(columns=['target'])
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    min_samples_leaf=5,
    min_samples_split=10
)

model.fit(X_train, y_train)

predictions = model.predict(X_test)

result_analysis = pd.DataFrame({
    'Actual': y_test,
    'Predicted': predictions
})

print("Accuracy: ", accuracy_score(y_test, predictions))
print("Classification Report: ", classification_report(y_test, predictions))

result_analysis.head(5)

Accuracy:  0.9333333333333333
Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

     Actual  Predicted
38        0          0
127       2          2
57        1          1
93        1          1
42        0          0